export const optionsStack = [
  {
    label: 'Frontend',
    items: [
      { label: 'Angular', value: 'Angular' },
      { label: 'Astro', value: 'Astro' },
      { label: 'Bootstrap', value: 'Bootstrap' },
      { label: 'CSS', value: 'CSS' },
      { label: 'HTML', value: 'HTML' },
      { label: 'JavaScript', value: 'JavaScript' },
      { label: 'Material UI', value: 'MUI' },
      { label: 'Next.js', value: 'Next.js' },
      { label: 'Nuxt.js', value: 'Nuxt.js' },
      { label: 'PrimeReact', value: 'PrimeReact' },
      { label: 'React', value: 'React' },
      { label: 'Remix', value: 'Remix' },
      { label: 'Sass/SCSS', value: 'Sass' },
      { label: 'shadcn/ui', value: 'shadcn/ui' },
      { label: 'Svelte', value: 'Svelte' },
      { label: 'SvelteKit', value: 'SvelteKit' },
      { label: 'TailwindCSS', value: 'TailwindCSS' },
      { label: 'TypeScript', value: 'TypeScript' },
      { label: 'Vue.js', value: 'Vue.js' },
    ],
  },
  {
    label: 'Backend',
    items: [
      { label: '.NET Core', value: '.NET Core' },
      { label: 'C#', value: 'C#' },
      { label: 'Django', value: 'Django' },
      { label: 'Elixir/Phoenix', value: 'Elixir' },
      { label: 'Express.js', value: 'Express.js' },
      { label: 'FastAPI', value: 'FastAPI' },
      { label: 'Flask', value: 'Flask' },
      { label: 'Go', value: 'Go' },
      { label: 'Java (Spring Boot)', value: 'Java (Spring Boot)' },
      { label: 'Laravel', value: 'Laravel' },
      { label: 'NestJS', value: 'NestJS' },
      { label: 'Node.js', value: 'Node.js' },
      { label: 'PHP', value: 'PHP' },
      { label: 'Python', value: 'Python' },
      { label: 'Ruby on Rails', value: 'Ruby on Rails' },
      { label: 'Rust', value: 'Rust' },
      { label: 'tRPC', value: 'tRPC' },
    ],
  },
  {
    label: 'Databases & Caching',
    items: [
      { label: 'Cassandra', value: 'Cassandra' },
      { label: 'DynamoDB', value: 'DynamoDB' },
      { label: 'Elasticsearch', value: 'Elasticsearch' },
      { label: 'Firebase', value: 'Firebase' },
      { label: 'MariaDB', value: 'MariaDB' },
      { label: 'MongoDB', value: 'MongoDB' },
      { label: 'MySQL', value: 'MySQL' },
      { label: 'PostgreSQL', value: 'PostgreSQL' },
      { label: 'Redis', value: 'Redis' },
      { label: 'SQLite', value: 'SQLite' },
      { label: 'Supabase', value: 'Supabase' },
    ],
  },
  {
    label: 'Cloud Providers',
    items: [
      { label: 'AWS', value: 'AWS' },
      { label: 'Azure', value: 'Azure' },
      { label: 'DigitalOcean', value: 'DigitalOcean' },
      { label: 'Google Cloud (GCP)', value: 'GCP' },
      { label: 'Heroku', value: 'Heroku' },
      { label: 'Netlify', value: 'Netlify' },
      { label: 'Railway', value: 'Railway' },
      { label: 'Render', value: 'Render' },
      { label: 'Vercel', value: 'Vercel' },
    ],
  },
  {
    label: 'AWS Services',
    items: [
      { label: 'AWS API Gateway', value: 'AWS API Gateway' },
      { label: 'AWS CloudFront', value: 'AWS CloudFront' },
      { label: 'AWS DynamoDB', value: 'AWS DynamoDB' },
      { label: 'AWS EC2', value: 'AWS EC2' },
      { label: 'AWS ECS Fargate', value: 'AWS ECS Fargate' },
      { label: 'AWS Lambda', value: 'AWS Lambda' },
      { label: 'AWS RDS', value: 'AWS RDS' },
      { label: 'AWS S3', value: 'AWS S3' },
    ],
  },
  {
    label: 'DevOps & Infrastructure',
    items: [
      { label: 'Ansible', value: 'Ansible' },
      { label: 'CI/CD (GitHub Actions)', value: 'GitHub Actions' },
      { label: 'CI/CD (GitLab)', value: 'GitLab CI' },
      { label: 'Docker', value: 'Docker' },
      { label: 'Jenkins', value: 'Jenkins' },
      { label: 'Kubernetes', value: 'Kubernetes' },
      { label: 'Nginx', value: 'Nginx' },
      { label: 'Terraform', value: 'Terraform' },
    ],
  },
  {
    label: 'CMS / Headless',
    items: [
      { label: 'Contentful', value: 'Contentful' },
      { label: 'Directus', value: 'Directus' },
      { label: 'Sanity', value: 'Sanity' },
      { label: 'Strapi', value: 'Strapi' },
      { label: 'WordPress', value: 'WordPress' },
    ],
  },
  {
    label: 'Mobile',
    items: [
      { label: 'Expo', value: 'Expo' },
      { label: 'Flutter', value: 'Flutter' },
      { label: 'Ionic', value: 'Ionic' },
      { label: 'React Native', value: 'React Native' },
    ],
  },
  {
    label: 'Testing',
    items: [
      { label: 'Cypress', value: 'Cypress' },
      { label: 'Jest', value: 'Jest' },
      { label: 'Playwright', value: 'Playwright' },
      { label: 'Pytest', value: 'Pytest' },
      { label: 'React Testing Library', value: 'Testing Library' },
      { label: 'Vitest', value: 'Vitest' },
    ],
  },
  {
    label: 'State Management',
    items: [
      { label: 'Jotai', value: 'Jotai' },
      { label: 'MobX', value: 'MobX' },
      { label: 'Pinia', value: 'Pinia' },
      { label: 'Recoil', value: 'Recoil' },
      { label: 'Redux', value: 'Redux' },
      { label: 'Vuex', value: 'Vuex' },
      { label: 'Zustand', value: 'Zustand' },
    ],
  },
  {
    label: 'ORM / Database Tools',
    items: [
      { label: 'Drizzle', value: 'Drizzle' },
      { label: 'Prisma', value: 'Prisma' },
      { label: 'Sequelize', value: 'Sequelize' },
      { label: 'TypeORM', value: 'TypeORM' },
    ],
  },
  {
    label: 'Authentication',
    items: [
      { label: 'Auth0', value: 'Auth0' },
      { label: 'Clerk', value: 'Clerk' },
      { label: 'Firebase Auth', value: 'Firebase Auth' },
      { label: 'NextAuth.js', value: 'NextAuth.js' },
      { label: 'Supabase Auth', value: 'Supabase Auth' },
    ],
  },
  {
    label: 'APIs & Networking',
    items: [
      { label: 'GraphQL', value: 'GraphQL' },
      { label: 'gRPC', value: 'gRPC' },
      { label: 'REST API', value: 'REST API' },
      { label: 'WebSockets', value: 'WebSockets' },
    ],
  },
  {
    label: 'Build Tools & Bundlers',
    items: [
      { label: 'esbuild', value: 'esbuild' },
      { label: 'Turbopack', value: 'Turbopack' },
      { label: 'Vite', value: 'Vite' },
      { label: 'Webpack', value: 'Webpack' },
    ],
  },
  {
    label: 'Monorepo & Tools',
    items: [
      { label: 'ESLint', value: 'ESLint' },
      { label: 'Nx', value: 'Nx' },
      { label: 'Prettier', value: 'Prettier' },
      { label: 'Turborepo', value: 'Turborepo' },
    ],
  },
]
